---

- name: Enable overcommit_memory in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: "1"
  become: true
  become_user: root

- name: Download and extract redis source
  unarchive:
    remote_src: true
    src: http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
    dest: /tmp
    creates: /tmp/redis-{{ redis_version }}/
  become: true
  become_user: root

- name: Build redis
  command: make
  args:
    chdir: /tmp/redis-{{ redis_version }}
    creates: /tmp/redis-{{ redis_version }}/src/redis-server
  become: true
  become_user: root

- name: Install redis
  command: make install
  args:
    chdir: /tmp/redis-{{ redis_version }}
    creates: /usr/local/bin/redis-server
  notify: restart redis
  become: true
  become_user: root

- name: Setup redis config file
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    mode: "0600"
  notify: restart redis
  become: true
  become_user: root

- name: Setup redis systemd unit file
  template:
    src: redis.service.j2
    dest: /etc/systemd/system/redis.service
    mode: "0644"
  notify: restart redis
  become: true
  become_user: root

- name: Enable redis systemd unit at startup
  systemd:
    name: redis
    enabled: true
    daemon_reload: true
  become: true
  become_user: root
